@echo off
echo Cleaning up hanging Chrome processes...
taskkill /F /IM chrome.exe /T >nul 2>&1
echo Deleting old session to avoid lock errors...
rmdir /s /q .wwebjs_auth >nul 2>&1
echo Starting WhatsApp Bot Server...
node server.js
pause
